### ISSUE TITLE
低端机型不支持 Native Promise 有查证吗？

### ISSUE THREAD

**Issue by choyri** [Akiq2016/mini-programm-template#2]
稍微搜了下，没有相关案例。也没办法找到测试机测试。想知道楼主是怎么发现这个问题的。

**Comment by Akiq2016** [comment]
去年做小程序开发时 是测试到iPhone5不支持

**Comment by choyri** [comment]
[运行环境差异](https://developers.weixin.qq.com/miniprogram/dev/devtools/details.html) 里，Promise 从 iOS8 开始就是支持的，是不是楼主用了旧版的系统，😂。

**Comment by Akiq2016** [comment]
忘记了 很不幸当初推广公司小程序的时候 帮忙宣传的实习生有两台i5手机就直接不兼容了
------- edit -------
@choyri 
从产品使用群体角度去考虑，衡量觉得不存在会有这种兼容问题，可以不引入bluebird。
从技术层面去考虑，如果对promise的使用仅限于使用一些basic features，可以不引入bluebird。
------- edit -------
Promise related issue
[promise.all](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=000828ae4d0f58a044a604dc556000&highline=promise.all)
[iOS 8 下系统内核的Promise实现有问题](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=dabbd68fa60bb873c1227f0c30a16c96&highline=promise.all)
