### ISSUE TITLE
ES6相关问题

### ISSUE THREAD

**Issue by jessjava** [Akiq2016/mini-programm-template#3]
1.您文档里面是不是说在微信开发者工具中不能勾选 es6->es5 ，您写反了
2.麻烦您能分享一下小程序中 ES6 ES5的这个功能场景、以及手机端运行时依赖的环境情况。和 ES6之间的支持关系是个什么样子的，谢谢了。

**Comment by Akiq2016** [comment]
> 1.您文档里面是不是说在微信开发者工具中不能勾选 es6->es5 ，您写反了

是我写反了，多谢指正

> 2.麻烦您能分享一下小程序中 ES6 ES5的这个功能场景、以及手机端运行时依赖的环境情况。和 ES6之间的支持关系是个什么样子的，谢谢了。

es6 es5的功能场景？这个使用es5还是es6只是你个人编码的习惯而已。 手机端运行时依赖的环境情况以及es6的支持情况可以看[文档这一部分](https://developers.weixin.qq.com/miniprogram/dev/devtools/details.html) 建议多翻阅文档 多搜关键字

**Comment by jessjava** [comment]
感谢
